import { documents, memories, providers, researchItems, tasks, tools, workflows } from './platform-data.js';
import { planObjective, redact, selectProvider, summarizeDashboard, validatePlatform } from './core.js';

const nav=['Home','Agent','Automation','Connectors','Memory','Research','Documents','Usage','Settings'];
const icon={Home:'⌂',Agent:'🤖',Automation:'⏱',Connectors:'🔗',Memory:'🧠',Research:'🔎',Documents:'📄',Usage:'📊',Settings:'⚙'};
const root=document.getElementById('root');
let active='Home';
let draftedTask=null;

function html(value){return String(value).replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));}
function pill(text,tone='neutral'){return `<span class="pill ${tone}">${html(text)}</span>`;}
function card(title,body,emoji='•'){return `<section class="card"><div class="card-title"><span>${emoji}</span><h2>${html(title)}</h2></div>${body}</section>`;}
function taskRow(t){const tone=t.status==='COMPLETED'?'good':t.status==='FAILED'||t.status==='BLOCKED'?'bad':t.status==='WAITING'?'warn':'neutral';return `<article class="task"><div><strong>${html(t.agent)}</strong><p>${html(t.goal)}</p><small>${html(t.currentStep)}</small><div class="chips">${t.tools.map(tool=>pill(tool)).join('')}</div></div><div class="task-meta">${pill(t.status,tone)}<span>${t.retries} retries</span></div></article>`;}
function toolRow(t){return `<article class="tool"><div><strong>${html(t.name)}</strong><p>${html(t.description)}</p><small>${html(t.permission)} · ${t.timeoutMs}ms · ${html(t.retryPolicy)}</small></div>${pill(`${t.risk} risk`,t.risk==='low'?'good':t.risk==='medium'?'warn':'bad')}</article>`;}
function providerRow(p){return `<article class="connector"><div><strong>${html(p.name)}</strong><p>${html(p.quota)}</p><small>Fallback: ${html(p.fallback)} · latency target ${p.latencyTargetMs}ms · ${html(p.costRisk)}</small></div>${pill(p.status,p.status==='connected'?'good':p.status==='needs_key'?'warn':'bad')}</article>`;}
function renderHome(){const summary=summarizeDashboard();const best=selectProvider({text:true});return `<div class="grid two">${card('Chat',`<div class="chat"><div class="bubble ai">Hi — I can chat, research with citations, analyze documents, run bounded agent plans, and explain which tools need authorization. Current executable mode: <strong>${html(best.name)}</strong>.</div><div class="composer"><button aria-label="voice input" data-action="voice">🎙</button><button aria-label="attach file" data-action="docs">📎</button><input id="chat-input" placeholder="Ask, attach, or start an agent task…"><button class="primary" data-action="draft-chat">Send</button></div><div id="chat-result" class="result"></div></div><div class="quick"><button data-jump="Research">Research with citations</button><button data-jump="Documents">Analyze document</button><button data-jump="Agent">Start coding agent</button><button data-jump="Automation">Schedule workflow</button></div>`,'⌂')}${card('System snapshot',`<div class="metrics"><div><b>${summary.connectedProviders}</b><span>connected modes</span></div><div><b>${summary.highRiskTools}</b><span>high-risk tools gated</span></div><div><b>${summary.activeTasks}</b><span>active tasks</span></div><div><b>${summary.workflows}</b><span>workflows</span></div></div>${tasks.map(taskRow).join('')}`,'📊')}</div>`;}
function renderAgent(){return card('Agent command center',`<div class="agent-layout"><textarea id="objective" placeholder="Objective: describe the outcome, constraints, and allowed tools"></textarea><div class="controls"><button class="primary" data-action="plan">Plan safely</button><button>Pause</button><button>Cancel</button></div><div id="plan-output" class="result">${draftedTask?renderPlan(draftedTask):'No active drafted plan yet.'}</div></div>${tasks.map(taskRow).join('')}`,'🤖');}
function renderPlan(task){return `<strong>${html(task.agent)}</strong><p>${html(task.currentStep)}</p><ol>${task.plan.map(step=>`<li>${html(step)}</li>`).join('')}</ol><div class="chips">${task.tools.map(tool=>pill(tool)).join('')}</div>`;}
function renderAutomation(){return `<div class="grid two">${card('Workflows',workflows.map(workflow=>`<article class="workflow"><strong>${html(workflow.name)}</strong>${pill(workflow.status,workflow.status==='ready'?'good':workflow.status==='blocked'?'bad':'warn')}<p>Trigger: ${html(workflow.trigger)} · Next: ${html(workflow.nextRun)}</p><div class="chips">${workflow.actions.map(action=>pill(action)).join('')}</div><button>Retry</button><button>Pause/resume</button></article>`).join(''),'⏱')}${card('Execution history',tasks.filter(t=>t.agent.includes('Automation')||t.agent.includes('QA')).map(taskRow).join(''),'📊')}</div>`;}
function renderConnectors(){return `<div class="grid two">${card('Provider health',providers.map(providerRow).join(''),'🔗')}${card('MCP and tool registry',tools.map(toolRow).join(''),'🛡')}</div>`;}
function renderMemory(){return card('User-controlled memory',memories.map(m=>`<article class="memory">${pill(m.type)}<strong>${html(m.title)}</strong><p>${html(m.summary)}</p><div><button>Delete</button><button>Export</button></div></article>`).join('')+'<button>Reset all memory</button>','🧠');}
function renderResearch(){return card('Research engine',`<div class="pipeline">QUERY → SEARCH → FILTER → EXTRACT → CROSS-CHECK → SYNTHESIZE → CITE</div>${researchItems.map(item=>`<article class="research-item">${pill(item.classification,item.classification==='VERIFIED'?'good':item.classification==='INFERRED'?'warn':'bad')}<strong>${html(item.topic)}</strong><p>${html(item.summary)}</p><small>Citations: ${item.citations.map(html).join(', ')}</small></article>`).join('')}`,'🔎');}
function renderDocuments(){return card('Document intelligence',`<div class="dropzone">📎 Upload authorized documents for parse → chunk → index → retrieve → answer → cite.</div>${documents.map(document=>`<article class="document"><strong>${html(document.name)}</strong>${pill(document.status,'warn')}<p>Chunks: ${document.chunks}; citation policy: ${html(document.citations)}</p></article>`).join('')}`,'📄');}
function renderUsage(){const summary=summarizeDashboard();const health=validatePlatform();return card('Quota and fallback',`<div class="metrics"><div><b>${summary.providerCount}</b><span>providers</span></div><div><b>${summary.credentialRequired}</b><span>need credentials</span></div><div><b>${summary.citations}</b><span>research citations</span></div><div><b>${health.ok?'OK':'ERR'}</b><span>platform validation</span></div></div>${providers.map(providerRow).join('')}`,'📊');}
function renderSettings(){return `<div class="grid two">${card('Privacy and security','<ul class="clean"><li>Least-privilege OAuth connectors.</li><li>Secret redaction before audit logging.</li><li>Data export/delete and retention controls.</li><li>Prompt-injection-aware tool permissions.</li><li>TLS and server-side credential storage required for production APIs.</li></ul>','🔒')}${card('Voice and multimodal','<p>Microphone, speech recognition, text-to-speech, image, audio, video, and document analysis are permission-gated and degrade gracefully when unsupported.</p><p>Unsupported permissions remain visible as requirements instead of pretending integration is active.</p>','🔊')}</div>`;}
function content(){return active==='Home'?renderHome():active==='Agent'?renderAgent():active==='Automation'?renderAutomation():active==='Connectors'?renderConnectors():active==='Memory'?renderMemory():active==='Research'?renderResearch():active==='Documents'?renderDocuments():active==='Usage'?renderUsage():renderSettings();}
function wire(){document.querySelectorAll('[data-nav],[data-jump]').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.nav||button.dataset.jump;render();}));document.querySelector('[data-action="plan"]')?.addEventListener('click',()=>{const objective=document.getElementById('objective').value;draftedTask=planObjective(objective);document.getElementById('plan-output').innerHTML=renderPlan(draftedTask);});document.querySelector('[data-action="draft-chat"]')?.addEventListener('click',()=>{const input=document.getElementById('chat-input');const safe=redact(input.value||'');document.getElementById('chat-result').innerHTML=`Drafted local-safe response path for: <strong>${html(safe)}</strong>. Add provider credentials server-side to enable model inference.`;});document.querySelector('[data-action="voice"]')?.addEventListener('click',()=>{document.getElementById('chat-result').textContent='Voice requires microphone permission and provider speech support; local degraded mode cannot transcribe audio.';});document.querySelector('[data-action="docs"]')?.addEventListener('click',()=>{active='Documents';render();});}
function render(){root.innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><div class="logo">⚡</div><div><strong>Atlas Assistant</strong><span>secure agent workspace</span></div></div><nav>${nav.map(n=>`<button data-nav="${n}" class="${active===n?'active':''}"><span>${icon[n]}</span>${n}</button>`).join('')}</nav><div class="sidebar-foot">🛡 <span>No client-side API keys. OAuth and provider secrets belong server-side.</span></div></aside><main><header class="hero"><div>${pill('Production foundation','good')}<h1>${active==='Home'?'A simple front door for deep AI work':active}</h1><p>Chat, agents, connectors, memory, RAG, automation, usage controls, and privacy are unified behind visible status and permissions.</p></div><button class="primary" data-jump="Usage">↻ Health check</button></header>${content()}</main></div>`;wire();}

render();
